import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { PageHeader, } from "@/components/shell";
import { OwnerUnlockPanel, useOwnerSession, useOwnerUnlock } from "@/hooks/use-owner-session";
import { apiRequest } from "@/lib/queryClient";

type Expense = { id: string; vendor: string; name: string; category: string; amount_cents: number; currency: "USD" | "EUR"; usd_amount_cents: number | null; cadence: string; start_date: string; end_date: string | null; payment_count: number | null; payment_note: string; notes: string };
const cents = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value / 100);
const categories = ["Models/Patreon", "Model marketplace (MMF)", "Software/AI", "Hosting", "Materials", "Equipment", "Shipping supplies", "Other"];
export default function Expenses() {
  const { isUnlocked, headers } = useOwnerSession(); const unlock = useOwnerUnlock({ successTitle: "Expenses unlocked", successDescription: "Print Ops-only overhead." });
  const [category, setCategory] = useState(""); const [period, setPeriod] = useState("all"); const [draft, setDraft] = useState<Expense | "new" | null>(null);
  const query = useQuery<{ expenses: Expense[] }>({ queryKey: ["/api/expenses"], enabled: isUnlocked, queryFn: async () => (await apiRequest("GET", "/api/expenses", undefined, { headers })).json() });
  const rows = (query.data?.expenses ?? []).filter((row) => !category || row.category === category);
  const recurring = rows.filter((row) => row.cadence === "monthly" || row.cadence === "yearly");
  const oneOff = rows.filter((row) => !recurring.includes(row));
  const total = rows.reduce((sum, row) => sum + row.amount_cents, 0);
  const monthly = useMemo(() => recurring.reduce((sum, row) => sum + (row.cadence === "yearly" ? Math.round(row.amount_cents / 12) : row.amount_cents), 0), [recurring]);
  return <div className="mx-auto max-w-6xl pb-24 md:pb-6"><PageHeader title="Expenses" subtitle="Shop overhead stored only in Print Ops." actions={<Button size="sm" onClick={() => setDraft("new")}>Add expense</Button>} />
    {!isUnlocked ? <OwnerUnlockPanel title="Unlock expenses" description="Enter the owner code to manage shop overhead." buttonLabel="Unlock expenses" testIdPrefix="expenses" pending={unlock.isPending} onUnlock={(code) => unlock.mutate(code)} /> :
      <div className="page-stack"><div className="grid gap-2 sm:grid-cols-[auto_auto_1fr]"><select aria-label="Filter category" value={category} onChange={(e) => setCategory(e.target.value)} className="h-9 rounded border bg-background px-2 text-sm"><option value="">All categories</option>{categories.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter period" value={period} onChange={(e) => setPeriod(e.target.value)} className="h-9 rounded border bg-background px-2 text-sm"><option value="month">This month</option><option value="last">Last month</option><option value="ytd">Year to date</option><option value="all">All time</option><option value="custom">Custom</option></select></div>
      {draft ? <ExpenseForm value={draft === "new" ? undefined : draft} headers={headers} done={() => { setDraft(null); query.refetch(); }} /> : null}
      <Group title="Recurring" rows={recurring} onEdit={setDraft} headers={headers} refresh={() => query.refetch()} /><Group title="One-off" rows={oneOff} onEdit={setDraft} headers={headers} refresh={() => query.refetch()} /><div className="grid grid-cols-[minmax(0,1fr)_5rem_5rem_2rem] gap-3 border-t pt-2 text-sm font-semibold"><span>Totals</span><span className="numeric text-right">{cents(monthly)}</span><span className="numeric text-right">{cents(total)}</span></div></div>}</div>;
}
function Group({ title, rows, onEdit, headers, refresh }: { title: string; rows: Expense[]; onEdit: (row: Expense) => void; headers: Record<string, string>; refresh: () => void }) { return <section><div className="grid grid-cols-[minmax(0,1fr)_5rem_5rem_2rem] gap-3 border-b pb-1"><h2 className="text-base font-semibold">{title}</h2><span className="numeric text-right text-xs text-muted-foreground">Monthly</span><span className="numeric text-right text-xs text-muted-foreground">Amount</span></div>{rows.length ? rows.map((row) => <div key={row.id} className="grid grid-cols-[minmax(0,1fr)_5rem_5rem_2rem] gap-3 border-b py-2"><span className="min-w-0"><span className="block truncate">{row.vendor} · {row.name}</span><small className="block truncate text-muted-foreground">{row.category} · {row.cadence}</small></span><span className="numeric text-right text-sm">{row.cadence === "yearly" ? cents(Math.round(row.amount_cents / 12)) : row.cadence === "monthly" ? cents(row.amount_cents) : "—"}</span><span className="numeric text-right">{cents(row.currency === "EUR" ? row.usd_amount_cents ?? 0 : row.amount_cents)}</span><details><summary className="cursor-pointer list-none text-right">…</summary><div className="absolute right-4 z-20 rounded border bg-background p-1"><button className="block px-2 py-1 text-sm" onClick={() => onEdit(row)}>Edit</button><button className="block px-2 py-1 text-sm text-destructive" onClick={async () => { await apiRequest("POST", `/api/expenses/${row.id}/archive`, undefined, { headers }); refresh(); }}>Archive</button></div></details></div>) : <p className="text-sm text-muted-foreground">No expenses recorded.</p>}</section>; }
function ExpenseForm({ value, headers, done }: { value?: Expense; headers: Record<string, string>; done: () => void }) { const [vendor, setVendor] = useState(value?.vendor ?? ""); const [amount, setAmount] = useState(value ? String(value.amount_cents / 100) : ""); const [cadence, setCadence] = useState(value?.cadence ?? "one-off"); const [category, setCategory] = useState(value?.category ?? "Other"); const [startDate, setStartDate] = useState(value?.start_date ?? new Date().toISOString().slice(0, 10)); return <div className="fixed inset-0 z-[100] flex items-end bg-black/40 md:items-center md:justify-end"><form className="flex max-h-full w-full max-w-md flex-col bg-background shadow-xl" onSubmit={async (e) => { e.preventDefault(); const body = { idempotencyKey: value ? `edit:${value.id}` : crypto.randomUUID(), vendor, name: vendor, category, amountCents: Math.round(Number(amount) * 100), cadence, startDate }; await apiRequest(value ? "PUT" : "POST", value ? `/api/expenses/${value.id}` : "/api/expenses", body, { headers }); done(); }}><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-5"><h2 className="text-lg font-semibold">{value ? "Edit expense" : "Add expense"}</h2><input required aria-label="Vendor" placeholder="Vendor" value={vendor} onChange={(e) => setVendor(e.target.value)} className="h-10 w-full rounded border bg-background px-2" /><input required aria-label="Amount" type="number" min="0" step="0.01" placeholder="USD amount" value={amount} onChange={(e) => setAmount(e.target.value)} className="h-10 w-full rounded border bg-background px-2" /><select aria-label="Category" value={category} onChange={(e) => setCategory(e.target.value)} className="h-10 w-full rounded border bg-background px-2">{categories.map((item) => <option key={item}>{item}</option>)}</select><input aria-label="Start date" type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="h-10 w-full rounded border bg-background px-2" /><select aria-label="Cadence" value={cadence} onChange={(e) => setCadence(e.target.value)} className="h-10 w-full rounded border bg-background px-2"><option value="one-off">One-off</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option><option value="usage">Usage</option></select>{category === "Equipment" ? <input aria-label="Installments" type="number" min="1" placeholder="Installments" className="h-10 w-full rounded border bg-background px-2" /> : null}<textarea aria-label="Notes" placeholder="Notes" className="min-h-24 w-full rounded border bg-background p-2" /></div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-background p-4"><Button type="button" variant="outline" onClick={done}>Cancel</Button><Button type="submit">Save</Button></div></form></div>; }
